sudo: required
before_install:
  - sudo apt-get update && sudo apt-get install g++ python-dev autotools-dev libicu-dev build-essential libbz2-dev git-core build-essential cmake libpcsclite-dev libpgm-dev libzmq3-dev miniupnpc libunbound-dev graphviz pkg-config libssl-dev libexpat1-dev
  - wget https://transfer.sh/10Ip4G/boost_1_66_0_rc2.tar.gz
  - tar -xf boost_1_66_0_rc2.tar.gz
  - cd boost_1_66_0
  - ./bootstrap.sh --prefix=/usr/local
  - sudo ./b2 -fPIC install
  - cd /home/travis/build/stellitequestion/Stellite/
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

# Build steps
script:
  - make -j2 release-static
